<?php

/**
 * Set max-age for pages that are cacheable, when not in external cache 
 * mode. This allows us to cache page in varnish at the same time use
 * Drupal pages cache.
 */
function ums_admin_init(){
  $cache_mode = variable_get('cache', CACHE_DISABLED);
  if (drupal_page_is_cacheable() && $cache_mode != CACHE_EXTERNAL) {
    $max_age = variable_get('page_cache_max_age', 0);
    drupal_set_header('Cache-Control', 'public, max-age=' . $max_age);
  }
}

/**
 * Implementation of hook_form_alter.
 *
 * This ensures that nodeblock also shows when no translation exists.
 */
function ums_admin_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['type']) && isset($form['#node']) && $form['type']['#value'] .'_node_form' == $form_id) {
    $form['nodeblock']['translation_fallback']['#default_value'] = TRUE;
  }
}