<?php

/**
 * Implementation of hook_perm().
 */
function viewer3d_perm() {
  return array(
    'administer viewer',
    'administer route',
    'view model'
  );
}

/**
 * Implementation of hook_menu().
 */
function viewer3d_menu() {
  $items = array();

  $items['admin/settings/3dviewer'] = array(
    'title' => t('3D viewer'),
    'description' => t('Configure 3D viewer (flash model)'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('viewer3d_admin_form'),
    'access arguments' => array('administer viewer'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/viewer3d.admin.inc',
  );

  // Load settings
  $settings = variable_get('viewer3d', array());
  if (isset($settings['path'])) {
    $items[$settings['path']] = array(
      'title' => t('3D viewer'),
      'description' => t('Display 3D viewer'),
      'page callback' => 'viewer3d_page',
      'access arguments' => array('view model'),
      'type' => MENU_CALLBACK,
    );
  }

  return $items;
}

function viewer3d_page() {
  // Build settings array to set to jQuery.
  $path = drupal_get_path('module', 'viewer3d');
  $settings = variable_get('viewer3d', array());
  $settings['flash_location'] = $path;

  drupal_add_js(array('viewer3d' => $settings), 'setting');
  drupal_add_js($path . '/js/swfobject.js', 'module');
  drupal_add_js($path . '/js/viewer3d.js', 'module');

  // Create viewer placeholder.
  $output = '';
  $output .= '<div id="building-viewer-wrapper">';
  $output .= '<div id="building-viewer"></div>';
  $output .= '</div>';

  return $output;
}