<?php

/**
 * Implementation of hook_perm().
 */
function viewer3d_perm() {
  return array(
    'administer viewer',
    'administer route',
    'view model'
  );
}

function viewer3d_menu() {
  $items = array();

  $items['admin/settings/3dviewer'] = array(
    'title' => t('3D viewer'),
    'description' => t('Configure 3D viewer (flash model)'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('viewer3d_admin_form'),
    'access arguments' => array('administer viewer'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/viewer3d.admin.inc',
  );

  // Load settings
  $settings = variable_get('viewer3d', array());
  if (isset($settings['path'])) {
    $items[$settings['path']] = array(
      'title' => t('3D viewer'),
      'description' => t('Display 3D viewer'),
      'page callback' => 'viewer3d_page',
      'access arguments' => array('view model'),
      'type' => MENU_CALLBACK,
    );
  }

  return $items;
}

function viewer3d_page() {  
  
//<script type="text/javascript" src="<?php print $directory ?>/scripts/swfobject.js"></script>
//<script type="text/javascript">
//  swfobject.embedSWF("<?php print $directory ?>/3d-viewer/BuildingViewer.swf", "building-viewer", "940", "600", "10.0.0", "<?php print $directory ?>/scripts/expressInstall.swf",{DaluxBuildingViewServerURL:"http://prod.dalux.dk/mmhus/output/0806/&OverviewURL=http://prod.dalux.dk/mmhus/overview/&currentLocation=2&angle=-4&angle2=0&showTopBar=false&showLog=true"},{allowFullScreen:"true",allowScriptAccess:"sameDomain",wmode: "1"});
//
//  function gotoLocation(pos, angle1, angle2) {
//    var app = thisMovie('building-viewer');
//
//    app = getObject('building-viewer');
//    if (!app) {
//      app = getObject('BuildingViewer-name');
//    }
//
//    app.gotoLocation(pos, angle1, angle2);
//  }
//
//   function getObject(obj) {
//       var theObj;
//       if (document.all) {
//           if (typeof obj == "string") {
//               return document.all(obj);
//           } else {
//               return obj.style;
//           }
//       }
//       if (document.getElementById) {
//           if (typeof obj == "string") {
//               return document.getElementById(obj);
//           } else {
//               return obj.style;
//           }
//       }
//       return null;
//   }
//
//   function thisMovie(movieName) {
//       // IE and Netscape refer to the movie object differently.
//       // This function returns the appropriate syntax depending on the browser.
//
//       var IE = /*@cc_on!@*/false
//
//
//       if (IE) {
//        return window[movieName];
//       } else {
//        return window.document[movieName];
//       }
//   }
//
//  $(document).ready(function() {
//    $('#building-viewer-nav-wrapper li a').tipsy({gravity: 's',fade: true});
//  });
//
//</script>


  return 'fisk';
}