<?php

define('LANGSWITCH_SOURCE', 'da');
define('LANGSWITCH_SOURCE_TITLE', 'Danish');
define('LANGSWITCH_TRANS', 'en');
define('LANGSWITCH_TRANS_TITLE', 'English');
define('LANGSWITCH_FRONT_PAGE', TRUE);

function langswitch_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('Consistent Language Switch');
      $blocks[0]['cache'] = BLOCK_NO_CACHE;
    return $blocks;

    case 'view':
      $block['subject'] = t('Language');
      $block['content'] = langswitch_get_language_switch();
  }
  //end switch ($op)
  return $block;
}

/**
 * Find path the to translated node base on the current path.
 */
function langswitch_get_language_switch() {
  global $language;
  $langcode = $language->language;
  $path = $_GET['q'];

  // Test for special paths, such as views etc. Format 'src' => 'target'.
  $special = array(
    'nyheder' => array('da' => 'nyheder', 'en' => 'news'),
  );

  // Check if path is in the special array.
  if (isset($special[$path])) {
    if ($langcode == LANGSWITCH_SOURCE) {
      $link = l(t(LANGSWITCH_TRANS_TITLE), LANGSWITCH_TRANS . '/' . $special[$path][LANGSWITCH_TRANS], array('language' => LANGSWITCH_TRANS));
    }
    else {
      // For some reason the l() function is not working here.
      $link = '<a href="/' . $special[$path][LANGSWITCH_SOURCE] . '">' . t(LANGSWITCH_SOURCE_TITLE) . '</a>';
    }
  }
  else {
    // Translate node path, if on exists.
    $page = translation_path_get_translations($path);
    unset($page[$language->language]);

    if (!empty ($page)) {
      if (isset($page[LANGSWITCH_SOURCE])) {
        $link = l(t(LANGSWITCH_SOURCE_TITLE), drupal_get_path_alias($page[LANGSWITCH_SOURCE], LANGSWITCH_SOURCE), array('language' => LANGSWITCH_SOURCE));
      }
      else {
        $link = l(t(LANGSWITCH_TRANS_TITLE), LANGSWITCH_TRANS . '/' . drupal_get_path_alias($page[LANGSWITCH_TRANS], LANGSWITCH_TRANS), array('language' => LANGSWITCH_TRANS));
      }
    }
  }

  // Link to translation found.
  if ($link) {
    return '<ul class="language-switch"><li class="leaf">' . $link . '</li></ul>';
  }

  // No translation where found, send user to front page?
  if (LANGSWITCH_FRONT_PAGE) {
    if ($langcode == LANGSWITCH_SOURCE) {
      $link = $link = l(t(LANGSWITCH_TRANS_TITLE), LANGSWITCH_TRANS, array('language' => LANGSWITCH_TRANS));
    }
    else {
      $link = '<a href="/">' . t(LANGSWITCH_SOURCE_TITLE) . '</a>';
    }
    return '<ul class="language-switch"><li class="leaf">' . $link . '</li></ul>';
  }

  return;
}