<?php

// $Id: clicktale.module,v 1.1.2.6 2011/01/23 13:23:23 cableman0408 Exp $

/*
 * Implementation of hook_perm().
 */
function clicktale_perm() {
  return array('administer clicktale');
}

/**
 * Implementation of hook_menu().
 *
 */
function clicktale_menu() {
  // Build include path
  $path = drupal_get_path('module', 'clicktale') . '/includes';

  $items = array();
  $items['admin/settings/clicktale'] = array(
    'title' => 'Clicktale',
    'description' => t('Clicktale tracking service settings.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('clicktale_admin_settings_form'),
    'access arguments' => array('administer clicktale'),
    'file' => 'clicktale.admin.inc',
    'file path' => $path,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/settings/clicktale/account'] = array(
    'title' => 'Tracking code',
    'description' => t('Administrate you Clicktale account.'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );

  $items['admin/settings/clicktale/configuration'] = array(
    'title' => 'Configurations',
    'description' => t('Clicktale configuration.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('clicktale_admin_configuration_form'),
    'access arguments' => array('administer clicktale'),
    'file' => 'clicktale.admin.inc',
    'file path' => $path,
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );

  return $items;
}


/**
 * Adds clicktale top tracking code to the top of the page.
 *
 * @global object $user
 */
function clicktale_init() {
  // Get path to clicktale include code
  include_once drupal_get_path('module', 'clicktale') . '/includes/clicktale.helpers.inc';
  $path = realpath(clicktale_get_library_path()) . "/ClickTaleTop.php";

  // Should the tracking code be inserted
  if (clicktale_tracking_configuration()) {
    require_once($path);
  }
}

/**
 * Adds clicktale bottom tracking code to the bottom just befor </body> tag.
 *
 * @global object $user
 */
function clicktale_exit() {
  // Get path to clicktale include code
  include_once drupal_get_path('module', 'clicktale') . '/includes/clicktale.helpers.inc';
  $path = realpath(clicktale_get_library_path()) . "/ClickTaleBottom.php";

  // Should the tracking code be inserted
  if (clicktale_tracking_configuration()) {
    require_once($path);
  }
}
