<?php
// $Id: clicktale.module,v 1.1.2.7 2011/02/06 12:54:47 cableman0408 Exp $

/**
 * @file The menu callback and functions to insert the tracking code is defined
 * in this module file. The clicktale tracking code is inserted just after the
 * body tag using hook_init and the hook_exit is used for the bottom tracking
 * code.
 */

/*
 * Implementation of hook_perm().
 */
function clicktale_perm() {
  return array('administer clicktale');
}

/**
 * Implementation of hook_menu().
 *
 */
function clicktale_menu() {
  // Set the include path
  $path = drupal_get_path('module', 'clicktale') . '/includes';

  $items = array();
  $items['admin/settings/clicktale'] = array(
    'title' => 'Clicktale',
    'description' => t('Clicktale tracking service settings.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('clicktale_admin_settings_form'),
    'access arguments' => array('administer clicktale'),
    'file' => 'clicktale.admin.inc',
    'file path' => $path,
    'type' => MENU_NORMAL_ITEM,
  );

  // Basic settings menu callback
  $items['admin/settings/clicktale/account'] = array(
    'title' => 'Tracking code',
    'description' => t('Administrate you Clicktale account.'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );

  // Configuration menu callback
  $items['admin/settings/clicktale/configuration'] = array(
    'title' => 'Configurations',
    'description' => t('Clicktale configuration.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('clicktale_admin_configuration_form'),
    'access arguments' => array('administer clicktale'),
    'file' => 'clicktale.admin.inc',
    'file path' => $path,
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );

  return $items;
}


/**
 * Adds clicktale top tracking code to the top of the page just after the <body>
 * tag.
 *
 */
function clicktale_init() {
  // Load helper functions
  include_once drupal_get_path('module', 'clicktale') . '/includes/clicktale.helpers.inc';
  $path = realpath(clicktale_get_library_path()) . "/ClickTaleTop.php";

  // If the conditions are right the tracking code is inserted.
  if (clicktale_tracking_configuration()) {
    require_once($path);
  }
}

/**
 * Adds clicktale bottom tracking code to the bottom just befor </body> tag.
 *
 * @global object $user
 */
function clicktale_exit() {
  // Load helper functions
  include_once drupal_get_path('module', 'clicktale') . '/includes/clicktale.helpers.inc';
  $path = realpath(clicktale_get_library_path()) . "/ClickTaleBottom.php";

  // If the conditions are right the tracking code is inserted.
  if (clicktale_tracking_configuration()) {
    require_once($path);
  }
}
